### ISSUE TITLE
Option to set history limit

### ISSUE THREAD

**Issue by dsx** [Rouji/Hupl#16]
It would be nice to have an option to set history limit (or disable history completely).

**Comment by Rouji** [comment]
true

**Comment by Rouji** [comment]
https://github.com/Rouji/Hupl/commit/51e5d54ee37cc02ee0c2ef94f132b379e5c4b0c7 should do the job

I skipped the explicit limit on/off and went with just a default value, because the history view crashes the app anyway if you go a bit above that :shrug:

**Comment by dsx** [comment]
Thank you!
