### ISSUE TITLE
android.os.TransactionTooLargeException: data parcel size 2708712 bytes

### ISSUE THREAD

**Issue by csprr** [Rouji/Hupl#21]
Hi,

On my S24+ (Android 14) I'm currently getting the following error while trying to upload anything.
While googling for this, I'm only finding solutions in the code, so not something I can do myself or on the phone.

![image](https://github.com/Rouji/Hupl/assets/38324207/53a2b759-6e79-406c-aac5-a7610f49a117)

**Comment by csprr** [comment]
Eh, my bad. Not an issue.
I've tried it on another phone, same issue. But then I found out that the imported uploader file did not contain the full uploader url, causing this issue apparently.
After changed the url, it worked fine again.

**Comment by Rouji** [comment]
Hmm that could do with better error handling though, tbh. Not exactly obvious what that exception means

**Comment by csprr** [comment]
> Hmm that could do with better error handling though, tbh. Not exactly obvious what that exception means

That I do agree on indeed.
Initially when googling it made me think that it had something to so with the intents and that a new Android version might have had things changed.
I'm glad that's not the case though.

**Comment by Rouji** [comment]
What exactly was wrong with the URL?

**Comment by csprr** [comment]
> What exactly was wrong with the URL?

I simply imported the hupl import from the single php filehost and called it a day. But it's an older version that only returns the base URL, so the php file was missing from the config.
So instead of https://image.example.tld/singlefileupload.php it only had https://image.example.tld, essentially just pointing at a complete wrong page.
