### ISSUE TITLE
build.gradle files missing

### ISSUE THREAD

**Issue by matejdro** [Rouji/Hupl#24]
Hello,

it appears that `build.gradle` files are missing from the project, which prevents it from being built from source.

Any chance you can include those? Thanks

**Comment by Rouji** [comment]
huh, that's odd  
yeah I'll do that asap when I get home

**Comment by Rouji** [comment]
@matejdro should be good now(?)  70ba647fba3b3c74bf9814a55caa0a1eb0a27c26

**Comment by matejdro** [comment]
@Rouji `app/build.gradle.kts` is still missing.

Can you please try checking out the project into a blank directory and building it? That way you can determine what else might be missing

**Comment by Rouji** [comment]
f878da46247342f03703c53ddff0cd0e03b977e2 somehow missed that one, sry

**Comment by matejdro** [comment]
Now it works, thanks!
