### ISSUE TITLE
Default hoster

### ISSUE THREAD

**Issue by Rouji** [Rouji/Hupl#7]
Let the user pick a default one to always use, without having to select it for every single upload(?)

**Comment by Rouji** [comment]
Turns out it's actually kind of annoying whenever you do want to change uploader.

**Comment by FichteFoll** [comment]
Since the current interface also has a checkbox on whether to resize images or not, the extra step is needed anyway and showing the uploader selection in the same screen doesn't hurt.

A default uploader would only make sense if that checkbox also gets a default value.

**Comment by Rouji** [comment]
The checkbox actually already remembers if you ticked it before or not, so that's not a problem. But I tried a (really hacky) version of a default uploader feature and noticed I change the resize option really quite often for different uploads. So setting a default got on my tits more than it saved me any time.

I guess if someone really wants that feature anyway I can have another look at it, but for me I just don't see any value in it.

**Comment by FichteFoll** [comment]
Yes, that's what I wanted to say.
